<?php
require 'db.php';
require 'mfa.php';

if (!isset($_SESSION['user_id'])) {
    header("Location: index.php");
    exit();
}

$user_id = $_SESSION['user_id'];
$success = "";
$error = "";

// Get user's current MFA status
$stmt = mysqli_prepare($conn, "SELECT mfa_secret FROM users WHERE id = ?");
mysqli_stmt_bind_param($stmt, "i", $user_id);
mysqli_stmt_execute($stmt);
$result = mysqli_stmt_get_result($stmt);
$user = mysqli_fetch_assoc($result);
$has_mfa = !empty($user['mfa_secret']);

if ($_SERVER['REQUEST_METHOD'] == 'POST') {
    if (isset($_POST['action']) && $_POST['action'] == 'disable') {
        $stmt = mysqli_prepare($conn, "UPDATE users SET mfa_secret = NULL WHERE id = ?");
        mysqli_stmt_bind_param($stmt, "i", $user_id);
        mysqli_stmt_execute($stmt);
        $success = "2FA has been disabled.";
        $has_mfa = false;
        logActivity($user_id, "MFA_DISABLED", "User disabled 2FA");
    } elseif (isset($_POST['action']) && $_POST['action'] == 'enable') {
        $secret = $_POST['mfa_secret'];
        $code = $_POST['mfa_code'];
        
        if (MFA::verifyCode($secret, $code)) {
            $stmt = mysqli_prepare($conn, "UPDATE users SET mfa_secret = ? WHERE id = ?");
            mysqli_stmt_bind_param($stmt, "si", $secret, $user_id);
            mysqli_stmt_execute($stmt);
            $success = "2FA has been successfully enabled!";
            $has_mfa = true;
            logActivity($user_id, "MFA_ENABLED", "User enabled 2FA");
        } else {
            $error = "Invalid verification code. Please try again.";
        }
    }
}

// Generate a new secret if we are showing the setup form
$new_secret = "";
if (!$has_mfa) {
    $new_secret = MFA::generateSecret();
    $qr_url = "https://chart.googleapis.com/chart?chs=200x200&chld=M|0&cht=qr&chl=" . urlencode("otpauth://totp/SecurePortal:" . $_SESSION['user_name'] . "?secret=" . $new_secret . "&issuer=SecurePortal");
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Setup 2FA - Secure Portal</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-100 p-8">
    <a href="settings.php" class="text-blue-600 underline">&larr; Back to Settings</a>
    
    <div class="max-w-md mx-auto mt-12 bg-white p-8 rounded shadow">
        <h2 class="text-2xl font-bold mb-6">Two-Factor Authentication</h2>

        <?php if ($success): ?>
            <p class="bg-green-100 text-green-700 p-3 rounded mb-4"><?php echo $success; ?></p>
        <?php endif; ?>

        <?php if ($error): ?>
            <p class="bg-red-100 text-red-700 p-3 rounded mb-4"><?php echo $error; ?></p>
        <?php endif; ?>

        <?php if ($has_mfa): ?>
            <p class="mb-4 text-green-600 font-medium">You currently have 2FA enabled on your account.</p>
            <form method="POST">
                <input type="hidden" name="action" value="disable">
                <button type="submit" class="w-full bg-red-600 text-white p-2 rounded hover:bg-red-700 font-bold" onclick="return confirm('Are you sure you want to disable 2FA?');">Disable 2FA</button>
            </form>
        <?php else: ?>
            <div class="mb-4 text-gray-700">
                <p class="mb-2">1. Install Google Authenticator or Authy on your mobile device.</p>
                <p class="mb-2">2. Scan the QR code below or enter the secret key manually.</p>
                
                <div class="flex justify-center my-4">
                    <img src="<?php echo $qr_url; ?>" alt="QR Code">
                </div>
                
                <p class="text-center font-mono bg-gray-100 p-2 rounded mb-4 tracking-widest text-lg"><?php echo $new_secret; ?></p>
                
                <p class="mb-2">3. Enter the 6-digit code generated by the app to verify setup.</p>
            </div>
            
            <form method="POST" class="space-y-4">
                <input type="hidden" name="action" value="enable">
                <input type="hidden" name="mfa_secret" value="<?php echo $new_secret; ?>">
                <div>
                    <input type="text" name="mfa_code" required pattern="\d{6}" maxlength="6" class="mt-1 block w-full border border-gray-300 rounded-md p-2 text-center text-xl tracking-widest" placeholder="000000">
                </div>
                <button type="submit" class="w-full bg-blue-600 text-white p-2 rounded hover:bg-blue-700 font-bold">Verify & Enable 2FA</button>
            </form>
        <?php endif; ?>
    </div>
</body>
</html>
