sonar.projectKey=Software-Security
sonar.projectName=Secure Student Portal
sonar.projectVersion=1.0

# Path to source directories (required)
sonar.sources=.

# Exclusions
sonar.exclusions=vendor/**, node_modules/**

# Language
sonar.language=php

# Encoding
sonar.sourceEncoding=UTF-8
